version: '3.8'
services:
  frontend-prod:
    restart: always
    image: "yizhouli/portfolio-frontend:lasted"
    ports:
      - "8086:80"
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf
      - ./config/conf.d:/etc/nginx/conf.d

    environment:
      - NODE_ENV=prod
